/** bench.json shape and its README rendering. VERIFIED: pure, so `make bench` regenerates the section. (bench.test.ts) */
import { TARGET_LANGUAGES } from "./dataset.ts";
import { KS, round, type RecallAtK, type RecallMatrix, type Reproduction, type Summary } from "./metrics.ts";
import type { ModelKey } from "./models.ts";
import type { ModelResult } from "./runner.ts";

export const BENCH_SCHEMA = "defuss-vectorsearch-bench.v1";
export const README_START = "<!-- bench:start -->";
export const README_END = "<!-- bench:end -->";

export type EnvironmentKey = "node" | "chromium";
export type PublishedModelResult = Omit<ModelResult, "sample">;

export interface BenchReport {
  readonly schema: typeof BENCH_SCHEMA;
  readonly generatedAt: string;
  readonly host: { readonly cpu: string; readonly cores: number; readonly platform: string };
  readonly dataset: {
    readonly name: string;
    readonly sha256: string;
    readonly languages: readonly string[];
    readonly haystack: number;
    readonly queries: number;
  };
  readonly ks: readonly number[];
  readonly environments: Record<
    EnvironmentKey,
    { readonly runtime: string; readonly models: Record<ModelKey, PublishedModelResult> }
  >;
  /** Cosine between Node and Chromium vectors of the same passages. */
  readonly crossEnvironment: Record<ModelKey, { readonly samples: number; readonly minCosine: number; readonly meanCosine: number }>;
}

const ENV_LABEL: Record<EnvironmentKey, string> = { node: "Node.js", chromium: "Chromium" };
const MODEL_LABEL: Record<ModelKey, string> = { winzling: "Winzling", harrier: "Harrier" };
const STRATEGY_LABEL = { bruteforce: "bruteforce", turboquant: "TurboQuant" } as const;
const STRATEGIES = ["bruteforce", "turboquant"] as const;

const ms = (summary: Summary) => `${summary.mean.toFixed(1)} (p95 ${summary.p95.toFixed(1)})`;
const row = (cells: readonly (string | number)[]) => `| ${cells.join(" | ")} |`;
const header = (cells: readonly string[], right = cells.length - 1) =>
  [row(cells), row(cells.map((_, i) => (i < cells.length - right ? "---" : "---:")))].join("\n");

const entries = <T>(record: Record<string, T>) => Object.entries(record) as [string, T][];

const at = <T>(byLanguage: Record<string, T>, language: string): T => {
  const value = byLanguage[language];
  if (value === undefined) throw new Error(`bench.json has no results for target language ${language}`);
  return value;
};

/**
 * Overall recall over the target languages' queries. VERIFIED: the dataset validator requires every query in every
 * language, so each language holds the same number of queries and the plain mean of per-language values is exact.
 */
export const targetRecall = (recall: RecallMatrix, targets: readonly string[]): RecallAtK =>
  Object.fromEntries(KS.map((k) => [
    `@${k}`,
    round(targets.reduce((sum, language) => sum + at(recall.byLanguage, language)[`@${k}`], 0) / targets.length, 1),
  ])) as RecallAtK;

export const targetReproduction = (reproduction: Reproduction, targets: readonly string[]): number =>
  round(targets.reduce((sum, language) => sum + at(reproduction.byLanguage, language), 0) / targets.length, 1);

/** Best first: compares R@3, then R@5, R@25 and R@100; ties keep the target list's order. */
export const byRecallDescending = (recall: RecallMatrix) => (a: string, b: string): number => {
  for (const k of KS) {
    const delta = at(recall.byLanguage, b)[`@${k}`] - at(recall.byLanguage, a)[`@${k}`];
    if (delta !== 0) return delta;
  }
  return 0;
};

export const renderReadmeSection = (report: BenchReport, targets: readonly string[] = TARGET_LANGUAGES): string => {
  const lines: string[] = [];
  const envs = entries(report.environments) as [EnvironmentKey, BenchReport["environments"][EnvironmentKey]][];
  lines.push(
    `Generated by \`make bench\` on ${report.generatedAt.slice(0, 10)} · ${report.host.cpu}, ${report.host.cores} cores, ${report.host.platform}.`,
    `Runtimes: ${envs.map(([env, data]) => `${ENV_LABEL[env]} ${data.runtime}`).join("; ")}.`,
    "",
    "### Embedding",
    "",
    "One text per call, warm session; model runtime = memory growth over load + embedding, without the held vectors:",
    "",
    header(["Environment", "Model", "Device", "Load ms", "Embed passage ms", "Embed query ms", "Model runtime MiB"], 4),
  );
  const results = envs.flatMap(([env, data]) =>
    (entries(data.models) as [ModelKey, PublishedModelResult][]).map(([model, result]) => ({ env, model, result })),
  );
  for (const { env, model, result } of results) {
    lines.push(row([ENV_LABEL[env], MODEL_LABEL[model], result.device, result.loadMs, ms(result.embedMs.passage), ms(result.embedMs.query), result.modelRuntimeMiB]));
  }
  const perStrategy = results.flatMap((entry) => STRATEGIES.map((strategy) => ({ ...entry, strategy, s: entry.result.strategies[strategy] })));
  lines.push(
    "",
    "### Retrieval Quality",
    "",
    `The ${targets.length} target languages: ${targets.map((code) => `\`${code}\``).join(", ")}; their ${report.dataset.queries / report.dataset.languages.length * targets.length} queries against all ${report.dataset.haystack} passages in ${report.dataset.languages.length} languages; R@k = % of queries whose gold passage ranks in the top k:`,
    "",
    header(["Environment", "Model", "Strategy", ...KS.map((k) => `R@${k}`), "Rank ±10%"], KS.length + 1),
  );
  for (const { env, model, strategy, s, result } of perStrategy) {
    const reproduced = strategy === "turboquant" ? `${targetReproduction(result.strategies.turboquant.rankReproduced10pct, targets)}%` : "n/a";
    const recall = targetRecall(s.recall, targets);
    lines.push(row([ENV_LABEL[env], MODEL_LABEL[model], STRATEGY_LABEL[strategy], ...KS.map((k) => recall[`@${k}`]), reproduced]));
  }
  lines.push(
    "",
    "### Cost per Method",
    "",
    "Passage = embed + share of the index build; query = embed + top-100 search; runtime = model runtime + index:",
    "",
    header(["Environment", "Model", "Strategy", "Passage ms", "Query ms", "Search ms mean", "Index build ms", "Runtime MiB", "Index MiB"], 6),
  );
  for (const { env, model, strategy, s } of perStrategy) {
    lines.push(row([ENV_LABEL[env], MODEL_LABEL[model], STRATEGY_LABEL[strategy], ms(s.passageMs), ms(s.queryMs), s.searchMs.mean.toFixed(3), s.indexMs.toFixed(1), s.runtimeMiB, s.indexMiB]));
  }
  const node = report.environments.node.models;
  const combos = (Object.keys(node) as ModelKey[]).flatMap((model) =>
    STRATEGIES.map((strategy) => ({ model, strategy })),
  );
  lines.push(
    "",
    "### Per Language, Node.js",
    "",
    `Target languages, best first by ${MODEL_LABEL[combos[0]!.model]} ${STRATEGY_LABEL[combos[0]!.strategy]}; cells: R@${KS.join(" / R@")}; Chromium and all ${report.dataset.languages.length} languages are in \`bench.json\`:`,
    "",
    header(["Language", ...combos.map(({ model, strategy }) => `${MODEL_LABEL[model]} ${STRATEGY_LABEL[strategy]}`)], 0),
  );
  const ranked = [...targets].sort(byRecallDescending(node[combos[0]!.model].strategies[combos[0]!.strategy].recall));
  for (const language of ranked) {
    lines.push(row([`\`${language}\``, ...combos.map(({ model, strategy }) => {
      const recall = node[model].strategies[strategy].recall.byLanguage[language]!;
      return KS.map((k) => recall[`@${k}`]).join(" / ");
    })]));
  }
  lines.push(
    "",
    `Node.js vs Chromium vectors for the same passages: ${(Object.keys(report.crossEnvironment) as ModelKey[])
      .map((model) => `${MODEL_LABEL[model]} min cosine ${report.crossEnvironment[model].minCosine} over ${report.crossEnvironment[model].samples} passages`)
      .join("; ")}.`,
  );
  return lines.join("\n");
};

/** Replaces the text between the bench markers; fails instead of appending when they are missing. */
export const replaceReadmeSection = (readme: string, section: string): string => {
  const start = readme.indexOf(README_START);
  const end = readme.indexOf(README_END);
  if (start < 0 || end < start) throw new Error(`README.md needs ${README_START} … ${README_END} markers`);
  return `${readme.slice(0, start + README_START.length)}\n${section}\n${readme.slice(end)}`;
};
